
import Pokemon.Batalha;
import Pokemon.Pokemon;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Gabriel
 */
public class EscolherPoke extends javax.swing.JFrame {

    /**
     * Creates new form EscolherPoke
     */
    public EscolherPoke() {
       // Pokemon.Batalha bat = new Pokemon.Batalha();
       // Pokemon.Pokemon poke = new Pokemon.Pokemon(nomeArg, tipoArg, NORMAL);
           
        initComponents();
        //BtnBatalha.setOpaque(false);
        //BtnBatalha.setContentAreaFilled(false);
        //BtnBatalha.setBorderPainted(false);
        BtnBatalha.setVisible(false);
        TxtAtaque.setVisible(false);
        TxtDefesa.setVisible(false);
        TxtVida.setVisible(false);
        txtTipo.setVisible(false);
        TxtAtaque2.setVisible(false);
        txtDefesa2.setVisible(false);
        txtVida2.setVisible(false);
        TxtTipo2.setVisible(false);
        Pokemon x;
        Batalha batalha;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BoxOpoPoke = new javax.swing.JComboBox<>();
        BoxMeusPoke = new javax.swing.JComboBox<>();
        lblImagemMeu = new javax.swing.JLabel();
        lblImagemOpo = new javax.swing.JLabel();
        BtnBatalha = new javax.swing.JButton();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        SpinMeuPokemon = new javax.swing.JSpinner();
        SpinOpoPoke = new javax.swing.JSpinner();
        TxtVida = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        TxtDefesa = new javax.swing.JTextField();
        TxtAtaque = new javax.swing.JTextField();
        TxtStats = new javax.swing.JLabel();
        txtTeste = new javax.swing.JLabel();
        txtVida2 = new javax.swing.JTextField();
        TxtAtaque2 = new javax.swing.JTextField();
        TxtTipo2 = new javax.swing.JTextField();
        txtDefesa2 = new javax.swing.JTextField();
        TxtStats2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(910, 490));
        getContentPane().setLayout(null);

        BoxOpoPoke.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pokemons", "Aggron", "Venusaur", "Gyarados", "Infernape" }));
        BoxOpoPoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxOpoPokeActionPerformed(evt);
            }
        });
        getContentPane().add(BoxOpoPoke);
        BoxOpoPoke.setBounds(600, 70, 120, 22);

        BoxMeusPoke.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pokemons", "Aggron", "Venusaur", "Gyarados", "Infernape" }));
        BoxMeusPoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxMeusPokeActionPerformed(evt);
            }
        });
        getContentPane().add(BoxMeusPoke);
        BoxMeusPoke.setBounds(190, 70, 120, 22);

        lblImagemMeu.setForeground(new java.awt.Color(0, 0, 0));
        lblImagemMeu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblImagemMeu);
        lblImagemMeu.setBounds(140, 190, 210, 240);
        getContentPane().add(lblImagemOpo);
        lblImagemOpo.setBounds(560, 190, 200, 240);

        BtnBatalha.setBackground(new java.awt.Color(230, 22, 0));
        BtnBatalha.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        BtnBatalha.setForeground(new java.awt.Color(51, 0, 0));
        BtnBatalha.setText("BORA PRO PAU!");
        BtnBatalha.setBorder(null);
        BtnBatalha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalhaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnBatalha);
        BtnBatalha.setBounds(350, 120, 220, 60);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ESCOLHA OS POKEMONS PARA A BATALHA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(7, 10, 900, 40);
        getContentPane().add(SpinMeuPokemon);
        SpinMeuPokemon.setBounds(110, 70, 64, 22);
        getContentPane().add(SpinOpoPoke);
        SpinOpoPoke.setBounds(730, 70, 64, 22);
        getContentPane().add(TxtVida);
        TxtVida.setBounds(10, 340, 100, 30);
        getContentPane().add(txtTipo);
        txtTipo.setBounds(10, 220, 100, 30);
        getContentPane().add(TxtDefesa);
        TxtDefesa.setBounds(10, 300, 100, 30);
        getContentPane().add(TxtAtaque);
        TxtAtaque.setBounds(10, 260, 100, 30);

        TxtStats.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TxtStats.setForeground(new java.awt.Color(255, 255, 255));
        TxtStats.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(TxtStats);
        TxtStats.setBounds(10, 170, 100, 40);

        txtTeste.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTeste.setForeground(new java.awt.Color(0, 0, 0));
        txtTeste.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(txtTeste);
        txtTeste.setBounds(190, 380, 530, 50);
        getContentPane().add(txtVida2);
        txtVida2.setBounds(790, 340, 100, 30);
        getContentPane().add(TxtAtaque2);
        TxtAtaque2.setBounds(790, 260, 100, 30);
        getContentPane().add(TxtTipo2);
        TxtTipo2.setBounds(790, 220, 100, 30);
        getContentPane().add(txtDefesa2);
        txtDefesa2.setBounds(790, 300, 100, 30);

        TxtStats2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TxtStats2.setForeground(new java.awt.Color(255, 255, 255));
        TxtStats2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(TxtStats2);
        TxtStats2.setBounds(790, 170, 100, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LEVEL");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(730, 30, 60, 60);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LEVEL");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 30, 60, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arena.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 910, 496);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BoxOpoPokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxOpoPokeActionPerformed
        if (BoxOpoPoke.getSelectedIndex() == 0){
            ImageIcon image = new ImageIcon(getClass().getResource("/resources/interrogação.png"));
            lblImagemOpo.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImagemOpo.getWidth(),lblImagemMeu.getHeight(), Image.SCALE_DEFAULT)));
        }
        if (BoxOpoPoke.getSelectedIndex() == 1){
            ImageIcon image = new ImageIcon(getClass().getResource("/resources/aggron.png"));
            lblImagemOpo.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImagemOpo.getWidth(),lblImagemMeu.getHeight(), Image.SCALE_DEFAULT)));
        }
        if (BoxOpoPoke.getSelectedIndex() == 2){
            ImageIcon image = new ImageIcon(getClass().getResource("/resources/veno.png"));
            lblImagemOpo.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImagemOpo.getWidth(),lblImagemMeu.getHeight(), Image.SCALE_DEFAULT)));
        }
        if (BoxOpoPoke.getSelectedIndex() == 3){
            ImageIcon image = new ImageIcon(getClass().getResource("/resources/gyara.png"));
            lblImagemOpo.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImagemOpo.getWidth(),lblImagemMeu.getHeight(), Image.SCALE_DEFAULT)));
        }
        if (BoxOpoPoke.getSelectedIndex() == 4){
            ImageIcon image = new ImageIcon(getClass().getResource("/resources/macaco.png"));
            lblImagemOpo.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImagemOpo.getWidth(),lblImagemMeu.getHeight(), Image.SCALE_DEFAULT)));
        }
        if (BoxOpoPoke.getSelectedIndex() != 0 && BoxMeusPoke.getSelectedIndex() != 0){
            BtnBatalha.setVisible(true);
        }else{
            BtnBatalha.setVisible(false);
        }
    }//GEN-LAST:event_BoxOpoPokeActionPerformed

    private void BoxMeusPokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxMeusPokeActionPerformed
        if (BoxMeusPoke.getSelectedIndex() == 0){
            ImageIcon image = new ImageIcon(getClass().getResource("/resources/interrogação.png"));
            lblImagemMeu.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImagemMeu.getWidth(),lblImagemMeu.getHeight(), Image.SCALE_DEFAULT)));
        }
        if (BoxMeusPoke.getSelectedIndex() == 1){
            ImageIcon image = new ImageIcon(getClass().getResource("/resources/aggron.png"));
            lblImagemMeu.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImagemMeu.getWidth(),lblImagemMeu.getHeight(), Image.SCALE_DEFAULT)));
        }
        if(BoxMeusPoke.getSelectedIndex() == 2){
            ImageIcon image = new ImageIcon(getClass().getResource("/resources/veno.png"));
            lblImagemMeu.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImagemMeu.getWidth(),lblImagemMeu.getHeight(), Image.SCALE_DEFAULT)));
        }
        if(BoxMeusPoke.getSelectedIndex() == 3){
            ImageIcon image = new ImageIcon(getClass().getResource("/resources/gyara.png"));
            lblImagemMeu.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImagemMeu.getWidth(),lblImagemMeu.getHeight(), Image.SCALE_DEFAULT)));
        }
        if(BoxMeusPoke.getSelectedIndex() == 4){
            ImageIcon image = new ImageIcon(getClass().getResource("/resources/macaco.png"));
            lblImagemMeu.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImagemMeu.getWidth(),lblImagemMeu.getHeight(), Image.SCALE_DEFAULT)));
        }
        if (BoxOpoPoke.getSelectedIndex() != 0 && BoxMeusPoke.getSelectedIndex() != 0){
            BtnBatalha.setVisible(true);
        }else{
            BtnBatalha.setVisible(false);
        }
    }//GEN-LAST:event_BoxMeusPokeActionPerformed

    private void BtnBatalhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalhaActionPerformed
        TxtAtaque.setVisible(true);
        TxtDefesa.setVisible(true);
        TxtVida.setVisible(true);
        txtTipo.setVisible(true);
        TxtAtaque2.setVisible(true);
        txtDefesa2.setVisible(true);
        txtVida2.setVisible(true);
        TxtTipo2.setVisible(true);
        TxtStats2.setText("Stats");
        TxtStats.setText("Stats");
        Pokemon meuPokemon = null;
        Pokemon outroPokemon = null;
        switch (BoxMeusPoke.getSelectedIndex()) {
            case 1-> {
                int nivel = Integer.parseInt(SpinMeuPokemon.getValue().toString());
                meuPokemon = new  Pokemon("Aggron", "Pedra", nivel);
                txtTipo.setText("Tipo: "+ meuPokemon.getTipo());
                TxtDefesa.setText("Defesa: "+String.valueOf(meuPokemon.getDefesa()));
                TxtAtaque.setText("Ataque: "+String.valueOf(meuPokemon.getAtaque()));
                TxtVida.setText("Vida: "+String.valueOf(meuPokemon.getVida()));
                break;
            }
        
            case 2 ->{
                int nivel = Integer.parseInt(SpinMeuPokemon.getValue().toString());
                meuPokemon = new  Pokemon("Venosaur", "Planta", nivel);
                
                txtTipo.setText("Tipo: "+ meuPokemon.getTipo());
                TxtDefesa.setText("Defesa: "+String.valueOf(meuPokemon.getDefesa()));
                TxtAtaque.setText("Ataque: "+String.valueOf(meuPokemon.getAtaque()));
                TxtVida.setText("Vida: "+String.valueOf(meuPokemon.getVida()));
                break;
                
            }
            case 3 ->{
               int nivel = Integer.parseInt(SpinMeuPokemon.getValue().toString());
                meuPokemon = new  Pokemon("Gyarados", "Água", nivel);
                
                txtTipo.setText("Tipo: "+ meuPokemon.getTipo());
                TxtDefesa.setText("Defesa: "+String.valueOf(meuPokemon.getDefesa()));
                TxtAtaque.setText("Ataque: "+String.valueOf(meuPokemon.getAtaque()));
                TxtVida.setText("Vida: "+String.valueOf(meuPokemon.getVida()));
                break;       
                
            }
            case 4 ->{
                int nivel = Integer.parseInt(SpinMeuPokemon.getValue().toString());
                meuPokemon = new  Pokemon("Infernape", "Fogo", nivel);
                txtTipo.setText("Tipo: "+ meuPokemon.getTipo());
                TxtDefesa.setText("Defesa: "+String.valueOf(meuPokemon.getDefesa()));
                TxtAtaque.setText("Ataque: "+String.valueOf(meuPokemon.getAtaque()));
                TxtVida.setText("Vida: "+String.valueOf(meuPokemon.getVida()));
            }
            
            
                
        }
        
        switch (BoxOpoPoke.getSelectedIndex()) {
            case 1-> {
                int nivel = Integer.parseInt(SpinOpoPoke.getValue().toString());
                outroPokemon = new  Pokemon("Aggron", "Pedra", nivel);
                TxtTipo2.setText("Tipo: "+ outroPokemon.getTipo());
                txtDefesa2.setText("Defesa: "+String.valueOf(outroPokemon.getDefesa()));
                TxtAtaque2.setText("Ataque: "+String.valueOf(outroPokemon.getAtaque()));
                txtVida2.setText("Vida: "+String.valueOf(outroPokemon.getVida()));
                break;
            }
        
            case 2 ->{
                int nivel = Integer.parseInt(SpinOpoPoke.getValue().toString());
                outroPokemon = new  Pokemon("Venosaur", "Planta", nivel);
                TxtTipo2.setText("Tipo: "+ outroPokemon.getTipo());
                txtDefesa2.setText("Defesa: "+String.valueOf(outroPokemon.getDefesa()));
                TxtAtaque2.setText("Ataque: "+String.valueOf(outroPokemon.getAtaque()));
                txtVida2.setText("Vida: "+String.valueOf(outroPokemon.getVida()));
                break;
            }
            case 3 ->{
               int nivel = Integer.parseInt(SpinOpoPoke.getValue().toString());
                outroPokemon = new  Pokemon("Gyarados", "Água", nivel);
                TxtTipo2.setText("Tipo: "+ outroPokemon.getTipo());
                txtDefesa2.setText("Defesa: "+String.valueOf(outroPokemon.getDefesa()));
                TxtAtaque2.setText("Ataque: "+String.valueOf(outroPokemon.getAtaque()));
                txtVida2.setText("Vida: "+String.valueOf(outroPokemon.getVida()));
                break;       
            }
            case 4 ->{
                int nivel = Integer.parseInt(SpinOpoPoke.getValue().toString());
                outroPokemon = new  Pokemon("Infernape", "Fogo", nivel);
                TxtTipo2.setText("Tipo: "+ outroPokemon.getTipo());
                txtDefesa2.setText("Defesa: "+String.valueOf(outroPokemon.getDefesa()));
                TxtAtaque2.setText("Ataque: "+String.valueOf(outroPokemon.getAtaque()));
                txtVida2.setText("Vida: "+String.valueOf(outroPokemon.getVida()));
                break;
            }
           
                
        }
        String vencedor = new Batalha(meuPokemon, outroPokemon).getResultado();
                
                       
    }//GEN-LAST:event_BtnBatalhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscolherPoke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscolherPoke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscolherPoke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscolherPoke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscolherPoke().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxMeusPoke;
    private javax.swing.JComboBox<String> BoxOpoPoke;
    private javax.swing.JButton BtnBatalha;
    private javax.swing.JSpinner SpinMeuPokemon;
    private javax.swing.JSpinner SpinOpoPoke;
    private javax.swing.JTextField TxtAtaque;
    private javax.swing.JTextField TxtAtaque2;
    private javax.swing.JTextField TxtDefesa;
    private javax.swing.JLabel TxtStats;
    private javax.swing.JLabel TxtStats2;
    private javax.swing.JTextField TxtTipo2;
    private javax.swing.JTextField TxtVida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblImagemMeu;
    private javax.swing.JLabel lblImagemOpo;
    private javax.swing.JTextField txtDefesa2;
    private javax.swing.JLabel txtTeste;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtVida2;
    // End of variables declaration//GEN-END:variables
}
